import axios from 'axios';

export const  GET =  async (url,action,headers={})  => {
    try {
        const {data}=   await axios.get(`${url}/${action}`,headers);    
        return {
            Data:data,
            Error:false
        }
    } catch (error) {
        return {
            ErrorMessage:'Ocurri칩 un error inesperado',
            Error:true            
        }
    }
}


export const  POST =  async (url,baseapi,action,dataBody,headers,initialState={})  => {
      try {
        const result= await axios.post(`${url}/${baseapi}/${action}`,dataBody,{headers})        
        if(!result || !result.status){
            return  {
                Error:true,
                ErrorMessage:'Ha ocurrido un error de conexi칩n, por favor intente m치s tarde.'
            }
        }
        if(result.status===200){
            return  {
                Error:false,
                Data:result.data
            }
        }
      } catch (error) {
        if(!error.response){
            return {
                Error:true,
                ErrorMessage:'Ha ocurrido un error inesperado, por favor intente mas tarde.'
                
            }
        }
          if(parseInt(error.response.status)===401){
            return {
                Error:true,
                ErrorMessage:'Ha finalizado la sessi칩n',
                StatusCode:401
            }
          }
          
            return {
                Error:true,
                ErrorMessage:'Ha ocurrido un error.',
                StatusCode:parseInt(error.response.status)
            }
        
          
      }
}